[build]
  command = "npm run build:frontend"
  publish = "public"
  functions = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/server.js/:splat"
  status = 200

[[redirects]]
  from = "/uploads/*"
  to = "/server.js/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "."
